<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/config.php';
require_once __DIR__ . '/includes/functions.php';
require_once __DIR__ . '/auth/lib.php';
require_once __DIR__ . '/modules/calendar/contract.php';
auth_ensure_schema();
ensureCalendarSchema();
$pageTitle = 'Kalendarz miasta';
$bodyClass = 'calendar-page';
$calendarChronicle = calendarChronicleEntries();
$calendarCsrfToken = calendarPublicCsrfToken();
$calendarUser = auth_current_user();
require_once __DIR__ . '/includes/header.php';
?>
<link rel="stylesheet" href="<?= SITE_URL ?>/assets/css/calendar.css?v=2">
<main id="main-content" class="calendar-page-shell" data-calendar-api="<?= sanitize(SITE_URL) ?>/calendar-api.php">
    <div class="calendar-page-top"><div><span class="calendar-kicker">KALENDARZ MIEJSKI</span><h1>Wydarzenia miasta</h1><p>Planujemy razem. Zapisujemy to, co ważne dla Krosna Odrzańskiego.</p></div><button class="calendar-primary" type="button" data-open-add><span aria-hidden="true">+</span> Dodaj wydarzenie</button></div>
    <section class="calendar-toolbar" aria-label="Nawigacja kalendarza"><div class="calendar-month-nav"><button type="button" class="calendar-circle" data-month-prev aria-label="Poprzedni miesiąc">←</button><h2 data-month-label></h2><button type="button" class="calendar-circle" data-month-next aria-label="Następny miesiąc">→</button><button type="button" class="calendar-today" data-today>Dziś</button></div><div class="calendar-view-switch"><button type="button" class="is-active" data-view="month">Miesiąc</button><button type="button" data-view="week">Tydzień</button><button type="button" data-view="list">Lista</button><button type="button" class="calendar-export" data-export>↓ Drukuj / zapisz PDF</button></div></section>
    <section class="calendar-layout"><div class="calendar-panel"><div class="calendar-loading" data-calendar-loading role="status" aria-live="polite">Ładowanie kalendarza…</div><div data-calendar-view></div><div class="calendar-legend"><span><i class="legend-resident"></i>Mieszkańcy</span><span><i class="legend-culture"></i>Kultura</span><span><i class="legend-sport"></i>Sport</span><span><i class="legend-city"></i>Miasto</span><span>kliknij dzień, aby zobaczyć szczegóły</span></div></div><aside class="calendar-side"><section class="calendar-day-card"><div class="calendar-side-heading"><div><span class="calendar-kicker">WYBRANY DZIEŃ</span><h3 data-selected-heading></h3></div><button type="button" class="calendar-tag-button" data-open-mark aria-label="Oznacz dzień">♢</button></div><div data-selected-mark></div><div class="calendar-event-list" data-selected-events></div><button type="button" class="calendar-add-dashed" data-open-add>＋ Dodaj wydarzenie</button></section><section class="calendar-day-card calendar-chronicle-card"><div class="calendar-side-heading"><div><span class="calendar-kicker">KRONIKA MIASTA</span><h3>Wpisy na kalendarzu</h3></div><span class="calendar-book-icon">▤</span></div><p>Każdy zatwierdzony wpis Kroniki jest oznaczony w kalendarzu według daty utworzenia.</p><button type="button" class="calendar-secondary" data-open-chronicle>Przeglądaj Kronikę →</button></section></aside></section>
</main>
<div class="calendar-modal-backdrop" data-close-modal></div>
<section class="calendar-modal" data-modal="add" aria-labelledby="calendar-add-title" role="dialog" aria-modal="true"><button type="button" class="calendar-modal-close" data-close-modal>×</button><span class="calendar-kicker">NOWY WPIS</span><h2 id="calendar-add-title">Dodaj wydarzenie</h2><p>Wydarzenie zostanie przekazane do moderacji i utworzy wpis w Kronice Miasta.</p><form data-event-form enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?= sanitize($calendarCsrfToken) ?>"><input class="calendar-honeypot" name="website" tabindex="-1" autocomplete="off"><label>Tytuł wydarzenia<input required name="title" maxlength="180" placeholder="np. Sąsiedzkie śniadanie"></label><div class="calendar-form-grid"><label>Data<input required type="date" name="date" data-form-date></label><label>Godzina<input type="text" name="time" maxlength="20" placeholder="np. 18:00"></label></div><label>Miejsce<input name="place" maxlength="180" placeholder="np. Rynek"></label><label>Kategoria<select name="type"><option>Mieszkańcy</option><option>Kultura</option><option>Sport</option><option>Miasto</option><option>Przypomnienie</option></select></label><label>Podpis autora<input required name="author_signature" maxlength="120" value="<?= sanitize($calendarUser['username'] ?? '') ?>" placeholder="np. Anna z Krosna"></label><label>Treść wydarzenia<textarea required name="description" maxlength="10000" rows="7" placeholder="Opisz wydarzenie"></textarea></label><label>Zdjęcie główne<input type="file" name="image" accept="image/avif,image/jpeg,image/png,image/gif,image/webp"></label><label>Zdjęcia dodatkowe<input type="file" name="gallery[]" accept="image/avif,image/jpeg,image/png,image/gif,image/webp" multiple></label><span class="calendar-upload-hint">Do 6 dodatkowych zdjęć. JPG, PNG, GIF, WebP lub AVIF, zgodnie z limitem serwisu. System utworzy lokalne miniatury.</span><button class="calendar-primary calendar-submit" type="submit">Przekaż do moderacji</button><p class="calendar-form-message" data-form-message></p></form></section>
<section class="calendar-modal calendar-small-modal" data-modal="mark" aria-labelledby="calendar-mark-title" role="dialog" aria-modal="true"><button type="button" class="calendar-modal-close" data-close-modal>×</button><span class="calendar-kicker">OZNACZENIE DNIA</span><h2 id="calendar-mark-title">Podpisz dzień</h2><form data-mark-form><label>Podpis dnia<input required maxlength="120" name="mark" placeholder="np. Wieczór dla sąsiadów"></label><button class="calendar-primary calendar-submit" type="submit">Oznacz dzień</button></form></section>
<section class="calendar-modal calendar-chronicle-modal" data-modal="chronicle" aria-labelledby="calendar-chronicle-title" role="dialog" aria-modal="true"><button type="button" class="calendar-modal-close" data-close-modal>×</button><span class="calendar-kicker">KRONIKA MIASTA</span><h2 id="calendar-chronicle-title">Wpisy, które zostają</h2><div class="calendar-chronicle-search"><input placeholder="Szukaj w kronice" data-chronicle-search></div><div class="calendar-chronicle-list" data-chronicle-list></div></section>
<script type="application/json" id="calendar-chronicle-data"><?= json_encode($calendarChronicle, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?></script>
<script src="<?= SITE_URL ?>/assets/js/calendar.js?v=2" defer></script>
<?php require_once __DIR__ . '/includes/footer.php'; ?>
